# Generated by Django 4.2.6 on 2023-10-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, choices=[('L', 'On Leave'), ('P', 'Present'), ('H', 'Half Day')], default='P', max_length=16)),
                ('location', models.CharField(blank=True, choices=[('OFFICE', 'In Office'), ('SITE', 'On Site'), ('WFH', 'Work from Home')], default='OFFICE', max_length=16)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.employee')),
            ],
        ),
    ]
