# Generated by Django 4.2.6 on 2023-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_options_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('OFFICE', 'In Office'), ('SITE', 'On Site'), ('WFH', 'Work from Home')], default='NONE', max_length=16),
        ),
    ]
