# Generated by Django 4.2.6 on 2023-11-04 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employeeleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleave',
            name='total_cl',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='total_el',
        ),
        migrations.AddField(
            model_name='employee',
            name='total_cl',
            field=models.PositiveIntegerField(default=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_el',
            field=models.IntegerField(default=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
