# Generated by Django 5.0 on 2024-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_employeeleave_total_cl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('R&D', 'Research and Development'), ('ENG', 'Engineering'), ('MKT', 'Marketing'), ('SAL', 'Sales'), ('OPS', 'Operations')], default='R&D', max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('R&D_R&D Lead', 'Research and Development Lead'), ('R&D_R&D Engineer', 'Research and Development Engineer'), ('R&D_Machine Learning Engineer', 'Machine Learning Engineer'), ('R&D_Artificial Intelligence Engineer', 'Artificial Intelligence Engineer'), ('R&D_Robotics Engineer', 'Robotics Engineer'), ('ENG_Engineering Lead', 'Engineering Lead'), ('ENG_Software Developer', 'Software Developer'), ('ENG_Quality Assurance Engineer', 'Quality Assurance Engineer'), ('ENG_Network Engineer', 'Network Engineer'), ('ENG_Hardware Engineer', 'Hardware Engineer'), ('MKT_Marketing Lead', 'Marketing Lead'), ('MKT_Marketing Manager', 'Marketing Manager'), ('MKT_Marketing Analyst', 'Marketing Analyst'), ('MKT_SEO Specialist', 'SEO Specialist'), ('MKT_Social Media Manager', 'Social Media Manager'), ('SAL_Sales Lead', 'Sales Lead'), ('SAL_Sales Manager', 'Sales Manager'), ('SAL_Sales Representative', 'Sales Representative'), ('SAL_Sales Consultant', 'Sales Consultant'), ('SAL_Sales Support', 'Sales Support'), ('OPS_Operations Lead', 'Operations Lead'), ('OPS_Operations Manager', 'Operations Manager'), ('OPS_Operations Administrator', 'Operations Administrator'), ('OPS_Operations Technician', 'Operations Technician'), ('OPS_Operations Support', 'Operations Support')], default='R&D_R&D Lead', max_length=50),
        ),
    ]
