# Generated by Django 5.0 on 2024-01-27 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employee_department_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_sl',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_cl',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_el',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave',
            field=models.CharField(blank=True, choices=[('CL', 'Casual Leave'), ('EL', 'Earned Leave'), ('SL', 'Sick Leave')], default='CL', max_length=16),
        ),
    ]
